//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blagodat.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlagodatAlibekov195Entities2 : DbContext
    {
        public BlagodatAlibekov195Entities2()
            : base("name=BlagodatAlibekov195Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<product_agent> product_agent { get; set; }
        public virtual DbSet<product_agents> product_agents { get; set; }
        public virtual DbSet<productsale> productsale { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }

        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

        public static User CurentStaff = null;
    }
}
