//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blagodat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int Cost { get; set; }
        public int OrderTime { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Services { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime DateClose { get; set; }
        public int RentalTime { get; set; }
        public int ItemID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Items Items { get; set; }
    }
}
